workspace = { members = [ "iced_grid"] }
[package]
name = "skycalendar"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[dependencies]
iced = "0.12"
iced_grid  = { path = "./iced_grid" }