workspace = { members = [ "iced_grid"] }
[package]
name = "skycalendar"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[dependencies]
iced = "0.13"
iced_grid  = { path = "./iced_grid" }
iced_renderer = "0.13.0"
iced_tiny_skia = "0.13.0"

[lints.rust]
rust_2018_idioms = "deny"
